name: Universal gluestack-ui App (Expo and NextJs) | Start and Build

on:
  push:
    branches:
      - patch
  pull_request:
    branches:
      - patch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: universal
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Start Expo
        run: yarn start

      - name: Start Next
        run: yarn dev

      - name: Build Next
        run: yarn build
