name: Universal gluestack-ui App (Expo and NextJs) | Start and Build

on:
  push:
    branches:
      - patch
  pull_request:
    branches:
      - patch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: universal
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Build Next
        working-directory: ${{ env.working-directory }}
        run: yarn build:next

      - name: Start Expo on port 19007
        working-directory: ${{ env.working-directory }}
        run: |
          cd apps/expo-app && yarn start:web --port 19007 &
          echo $! > expo_pid.txt
          sleep 60 # Wait for Expo to start

      - name: Run tests
        working-directory: ${{ env.working-directory }}
        run: yarn test

      - name: Kill Expo server
        run: |
          kill $(cat expo_pid.txt)
